# [build]
# target = ["arm64e-apple-darwin", "arm64e-apple-ios"]
[target.aarch64-apple-darwin]
rustflags = [
  "-C",
  "link-arg=-fuse-ld=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld",
  "-C",
  "link-arg=-ld_new",
]

[build]
rustc-wrapper = "/opt/homebrew/bin/sccache"
[profile.profiling]
inherits = "release"
debug = true
